baseURL: "https://barnett617.github.io/wilson-blog/"
title: "Wilson's Blog"
paginate: 20
theme: PaperMod

buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true

minify:
  disableXML: true
  minifyOutput: true

taxonomies:
  category: categories
  tag: tags
  series: series

outputs:
  home:
    - HTML
    - RSS
    - JSON # is necessary

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: "Wilson's Blog"
  description: "Personal blogs and notes about web development and life"
  keywords: [Blog, Portfolio, PaperMod]
  # author: Wilson
  images: []
  DateFormat: "2006-01-02 15:04:05" # https://pkg.go.dev/time#pkg-constants
  defaultTheme: auto # dark, light
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  # ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowWordCount: true
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: true
  disableScrollToTop: false
  comments: true
  hidemeta: false
  hideSummary: false
  showtoc: true
  tocopen: false

  assets:
    disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    favicon: "favicon_io/favicon.ico"
    favicon16x16: "favicon_io/favicon16x16.png"
    favicon32x32: "favicon_io/favicon32x32.png"
    apple_touch_icon: "favicon_io/apple-touch-icon.png"
    safari_pinned_tab: "favicon_io/apple-touch-icon.png"

  label:
    text: "Wilson's Blog"
    icon: favicon_io/apple-touch-icon.png
    iconHeight: 35

  # profile-mode
  profileMode:
    enabled: false # needs to be explicitly set
    title: ExampleSite
    subtitle: "This is subtitle"
    imageUrl: "<img location>"
    imageWidth: 120
    imageHeight: 120
    imageTitle: my image
    buttons:
      - name: Posts
        url: posts
      - name: Tags
        url: tags

  # home-info mode
  homeInfoParams:
    Title: "你好 \U0001F44B"
    Content: >
        - 欢迎来到我的博客，我在这里记录关于技术和生活的一些思考和总结

        - 如果发现任何问题，欢迎到 [这里](https://github.com/barnett617/wilson-blog/issues) 向我反馈

  socialIcons:
    - name: juejin
      url: "https://juejin.cn/user/1644525123025933/posts?sort=popular"
    - name: zhihu
      url: "https://www.zhihu.com/people/magi617/answers/by_votes"
    - name: douban
      url: "https://www.douban.com/people/DavidMe/?_i=14468907ISm58V"
    - name: github
      url: "https://github.com/barnett617"

  analytics:
    google:
      SiteVerificationTag: "XYZabc"
    bing:
      SiteVerificationTag: "XYZabc"
    yandex:
      SiteVerificationTag: "XYZabc"

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: true # hide on single page

  editPost:
    URL: "https://github.com/barnett617/wilson-blog/tree/main/source/content"
    Text: "Suggest Changes" # edit text
    appendFilePath: true # to append file path to Edit link

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]

# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
pygmentsUseClasses: true
markup:
  highlight:
    anchorLineNos: false
    codeFences: true
    guessSyntax: true
    lineNos: false
    noClasses: false
    # https://xyproto.github.io/splash/docs/all.html
    style: onedark
    tabWidth: 2

services:
  disqus:
    shortname: wilson-8

defaultContentLanguage: zh
languages:
  zh:
    contentDir: content/zh
    languageCode: zh-Hans-CN
    languageDirection: ltr
    menu:
      main:
        # - name: 博客
        #   url: /posts/
        #   weight: 5
        # - name: 笔记
        #   url: /notes/
        #   weight: 10
        - name: 时间线
          url: /archives/
          weight: 20
        - name: 搜索
          url: /search/
          weight: 30
        - name: 标签分类
          url: /tags/
          weight: 40
        - name: 关于我
          url: /about/
          weight: 50
    languageName: 中文
    params:
      subtitle: Wilson的所思所想
      # make both posts and notes be collected into archives
      mainSections:
        - posts
        - notes
      ShareButtons: ["wechat", "x"] # To customize which share buttons to be enabled on page
      editPost:
        Text: "修改建议"
    title: Wilson's Blog
    weight: 1
  en:
    baseURL: "https://barnett617.github.io/wilson-blog/"
    contentDir: content/en
    languageCode: en-US
    languageDirection: ltr
    menu:
      main:
      # - name: Posts
      #   url: /posts/
      #   weight: 20
      - name: Archives
        url: /archives/
        weight: 20
      - name: Search
        url: /search/
        weight: 30
      - name: About
        url: /about/
        weight: 40
    languageName: English
    # https://gohugo.io/content-management/multilingual/#changes-in-hugo-01120
    params:
      subtitle: Content created by Wilson
      mainSections:
        - posts
        - notes
      homeInfoParams:
        Title: "Hi there \U0001F44B"
        Content: >
            - Welcome to Wilson's Blog

            - I write blogs and keep notes on this site
      socialIcons:
        - name: github
          url: "https://github.com/barnett617"
        - name: linkedin
          url: "https://www.linkedin.com/in/scorpioaoe/"
    title: Wilson's Blog
    weight: 2
 
