baseURL: "https://barnett617.github.io/wilson-blog/"
title: "Wilson's Blog"
paginate: 20
theme: PaperMod

buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true

minify:
  disableXML: true
  minifyOutput: true

taxonomies:
  category: categories
  tag: tags
  series: series

menu:
  main:
    - name: Posts
      url: /posts/
      weight: 5
    - name: Notes
      url: /notes/
      weight: 10
    - name: Archives
      url: /archives/
      weight: 20
    # - name: Categories
    #   url: /categories/
    #   weight: 10
    - name: Search
      url: /search/
      weight: 30
    - name: Tags
      url: /tags/
      weight: 40
    - name: About
      url: /about/
      weight: 50
    
    # - identifier: example
    #   name: example.org
    #   url: https://example.org
    #   weight: 40

outputs:
  home:
    - HTML
    - RSS
    - JSON # is necessary

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: "Param Title"
  description: "Param Description"
  keywords: [Blog, Portfolio, PaperMod]
  # author: Wilson
  images: []
  # DateFormat: "15 Oct 2023"
  defaultTheme: auto # dark, light
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowWordCount: true
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: true
  disableScrollToTop: false
  comments: true
  hidemeta: false
  hideSummary: false
  showtoc: true
  tocopen: false

  assets:
    disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    favicon: "favicon_io/favicon.ico"
    favicon16x16: "favicon_io/favicon16x16.png"
    favicon32x32: "favicon_io/favicon32x32.png"
    apple_touch_icon: "favicon_io/apple-touch-icon.png"
    safari_pinned_tab: "favicon_io/apple-touch-icon.png"

  label:
    text: "Wilson's Blog"
    icon: favicon_io/apple-touch-icon.png
    iconHeight: 35

  # profile-mode
  profileMode:
    enabled: false # needs to be explicitly set
    title: ExampleSite
    subtitle: "This is subtitle"
    imageUrl: "<img location>"
    imageWidth: 120
    imageHeight: 120
    imageTitle: my image
    buttons:
      - name: Posts
        url: posts
      - name: Tags
        url: tags

  # home-info mode
  homeInfoParams:
    Title: "Hi there \U0001F44B"
    Content: >
        - Welcome to Wilson's Blog

        - I write blogs and keep notes on this site

  socialIcons:
    # - name: twitter
    #   url: "https://twitter.com/"
    # - name: stackoverflow
    #   url: "https://stackoverflow.com"

    - name: github
      url: "https://github.com/barnett617"
    - name: juejin
      url: "https://juejin.cn/user/1644525123025933/posts"
    - name: zhihu
      url: "https://www.zhihu.com/people/magi617/answers"
    - name: douban
      url: "https://www.douban.com/people/DavidMe/?_i=14468907ISm58V"
    - name: linkedin
      url: "https://www.linkedin.com/in/scorpioaoe/"

  analytics:
    google:
      SiteVerificationTag: "XYZabc"
    bing:
      SiteVerificationTag: "XYZabc"
    yandex:
      SiteVerificationTag: "XYZabc"

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: true # hide on single page

  editPost:
    URL: "https://github.com/<path_to_repo>/content"
    Text: "Suggest Changes" # edit text
    appendFilePath: true # to append file path to Edit link

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]

# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
pygmentsUseClasses: true
markup:
  highlight:
    anchorLineNos: false
    codeFences: true
    guessSyntax: false
    lineNos: false
    noClasses: false
    style: onedark
    tabWidth: 4

services:
  disqus:
    shortname: wilson-8
